/* ===================== QUAL ESTUDO É ESTE? ===================== */
const QOPT=[["serie","Relato ou série de casos"],["transversal","Transversal"],["ecologico","Ecológico"],["cc","Caso-controle"],["coorte","Coorte"],["ecr","Ensaio clínico randomizado"],["quase","Quase-experimental"],["rs","Revisão sistemática"]];
const WHO={vida:"A vida, o paciente, o médico",sort:"O pesquisador, por sorteio",sem:"O pesquisador, sem sorteio"};
/* [texto, resposta, quem decidiu, unidade, tempo, comentário] — exemplos fictícios */
const VIG=[
 ["Pesquisadores visitaram 600 domicílios sorteados de um bairro. Na mesma visita, mediram a pressão arterial dos moradores e perguntaram sobre o consumo de sal.","transversal","vida","Indivíduo","Exposição e desfecho no mesmo momento","Amostra de uma população definida, tudo medido de uma vez: é um inquérito. Mede prevalência."],
 ["Foram identificadas 80 mulheres com trombose venosa e 160 mulheres sem trombose atendidas no mesmo hospital. Todas foram entrevistadas sobre o uso anterior de contraceptivos.","cc","vida","Indivíduo","Do desfecho para a exposição passada","A seleção foi pelo desfecho (com e sem trombose) e a exposição foi buscada no passado."],
 ["Trabalhadores de uma fábrica, sem doença respiratória no início, foram classificados conforme a exposição à poeira e reavaliados todos os anos, por dez anos.","coorte","vida","Indivíduo","Da exposição para o desfecho","Pessoas livres do desfecho, classificadas pela exposição e acompanhadas: dá para medir incidência."],
 ["Pacientes com enxaqueca foram sorteados para receber um novo fármaco ou placebo e acompanhados por 12 semanas.","ecr","sort","Indivíduo","Da intervenção para o desfecho","Quem definiu a exposição foi o sorteio. Essa é a marca do ensaio clínico randomizado."],
 ["Com dados do IBGE e do DATASUS, comparou-se a cobertura de saneamento básico com a taxa de internação por diarreia em 141 municípios.","ecologico","vida","Grupo (município)","Um momento","Só há números por município. Ninguém sabe se quem foi internado morava em casa sem saneamento."],
 ["Um artigo descreve cinco pacientes jovens que desenvolveram miocardite depois de usar um suplemento para emagrecer.","serie","vida","Indivíduo","Descrição da evolução","Só há casos, descritos em detalhe, sem grupo de comparação. Levanta a hipótese, não a testa."],
 ["Uma UBS implantou um programa de caminhada. A hemoglobina glicada dos participantes foi medida antes do programa e seis meses depois. Não houve grupo de comparação.","quase","sem","Indivíduo","Antes e depois da intervenção","O pesquisador aplicou a intervenção, mas sem sorteio nem controle: é um estudo antes e depois. História natural e regressão à média entram na conta."],
 ["Em prontuários de 2010, pesquisadores separaram os funcionários de um hospital que trabalhavam no turno da noite e no turno do dia. Depois verificaram, nos registros até 2025, quem desenvolveu diabetes.","coorte","vida","Indivíduo","Da exposição para o desfecho, em registros","A seleção foi pela exposição (o turno), não pelo desfecho. Feita com registros do passado, é uma coorte retrospectiva."],
 ["Os autores registraram um protocolo, buscaram em cinco bases todos os ensaios sobre um antidepressivo, avaliaram o risco de viés de cada um e combinaram os resultados.","rs","—","Estudos já publicados","—","Não é um estudo primário: é uma pesquisa sobre pesquisas, com protocolo, busca exaustiva e síntese (aqui, com metanálise)."],
 ["Em uma escola, as turmas da manhã receberam um programa de educação alimentar e as da tarde não, por decisão da direção. O IMC dos alunos foi comparado ao fim do ano.","quase","sem","Indivíduo","Da intervenção para o desfecho","Há intervenção e grupo de comparação, mas sem sorteio: os grupos podem ser diferentes desde o início (controle não equivalente)."],
 ["Trinta UBS foram sorteadas: metade passou a usar um aplicativo de lembretes de consulta e metade manteve a rotina. Comparou-se a proporção de faltas.","ecr","sort","Conglomerado (UBS)","Da intervenção para o desfecho","Parece ecológico porque a unidade é a UBS, mas a exposição foi definida por sorteio: é um ensaio randomizado por conglomerados."],
 ["Em uma maternidade, 300 gestantes fizeram no mesmo dia um teste rápido e o exame padrão de referência, para estimar sensibilidade e especificidade.","transversal","vida","Indivíduo","Teste e referência no mesmo momento","Acurácia diagnóstica se mede em estudo transversal: teste-índice e padrão de referência aplicados juntos."],
 ["Depois de um surto de gastroenterite em uma festa, a vigilância entrevistou 45 pessoas que adoeceram e 90 convidados que não adoeceram sobre o que comeram.","cc","vida","Indivíduo","Do desfecho para a exposição passada","Em surtos, parte-se de quem adoeceu e de quem não adoeceu e investigam-se as exposições: rápido e com poucos participantes."],
 ["Um estudo comparou o consumo médio de refrigerante por habitante com a prevalência de obesidade em 30 países.","ecologico","vida","Grupo (país)","Um momento","Médias por país. Não dá para dizer que as pessoas que bebem mais refrigerante são as obesas."]];
const QZ={order:[],i:0,ans:null,ok:0,done:0};
function qzNew(){QZ.order=shuffle(VIG.map((_,i)=>i),rng(Date.now()%1e9));QZ.i=0;QZ.ans=null;QZ.ok=0;QZ.done=0;}
LAB("quiz","Reconhecer","Qual estudo é este?",`
<div class="intro"><span class="eyebrow">Reconhecer · prática</span><h2>Leia o resumo e diga qual é o desenho</h2><p>São 14 estudos fictícios. Antes de responder, faça as três perguntas: quem decidiu a exposição, qual é a unidade de análise e como o tempo entra.</p></div>
<div class="grid"><div class="card">
 <div class="row" style="justify-content:space-between"><span class="eyebrow" id="qzN"></span><span class="score" id="qzS"></span></div>
 <div class="progress"><i id="qzP"></i></div>
 <div id="qzB" style="margin-top:14px"></div>
</div></div>`,()=>{qzNew();
  $("qzB").addEventListener("click",e=>{const b=e.target.closest("[data-a]");if(b&&QZ.ans==null){QZ.ans=b.dataset.a;QZ.done++;if(QZ.ans===VIG[QZ.order[QZ.i]][1])QZ.ok++;renderQZ();}
    if(e.target.id==="qzNext"){QZ.i++;QZ.ans=null;renderQZ();}if(e.target.id==="qzAgain"){qzNew();renderQZ();}});
},()=>renderQZ());
function renderQZ(){const n=VIG.length;$("qzS").textContent=QZ.done?`${QZ.ok} de ${QZ.done} certas`:"";$("qzP").style.width=(QZ.done/n*100)+"%";
  if(QZ.i>=n){$("qzN").textContent="Fim";$("qzB").innerHTML=`<p class="q">Você acertou ${QZ.ok} de ${n}.</p><p class="lede">${QZ.ok===n?"Nenhum desenho escapou.":"Os erros mais comuns são confundir coorte retrospectiva com caso-controle e ensaio por conglomerados com estudo ecológico. O critério é sempre o mesmo: por onde o estudo começou e quem definiu a exposição."}</p><button class="btn primary" id="qzAgain">Jogar de novo</button>`;return;}
  const V=VIG[QZ.order[QZ.i]],a=QZ.ans;$("qzN").textContent=`Estudo ${QZ.i+1} de ${n}`;
  let h=`<p class="vig">${V[0]}</p><div class="quizopts">${QOPT.map(o=>`<button class="opt ${a==null?"":o[0]===V[1]?"right":o[0]===a?"wrong":""}" data-a="${o[0]}" ${a==null?"":"disabled"}>${o[1]}</button>`).join("")}</div>`;
  if(a!=null)h+=`<div class="fb"><b class="${a===V[1]?"ok":"no"}">${a===V[1]?"Isso mesmo.":"Não é esse."}</b> ${V[5]}<dl class="why"><dt>Quem decidiu a exposição</dt><dd>${WHO[V[2]]||V[2]}</dd><dt>Unidade de análise</dt><dd>${V[3]}</dd><dt>Tempo</dt><dd>${V[4]}</dd></dl></div><div class="row" style="margin-top:12px"><button class="btn primary" id="qzNext">${QZ.i===n-1?"Ver resultado":"Próximo estudo ›"}</button></div>`;
  $("qzB").innerHTML=h;}
