/* ===================== SAIBA MAIS das telas da versão 0.2 ===================== */
Object.assign(LEARN,{
rand:["Formas de randomizar",`<p>Um bom sorteio tem três propriedades:</p><ol><li><b>Imprevisível:</b> ninguém consegue antecipar a próxima alocação.</li><li><b>Equilibra em média</b> os fatores prognósticos conhecidos e desconhecidos.</li><li><b>É a base para a inferência:</b> as diferenças que sobram entre os grupos são acaso.</li></ol>
<h4>As formas</h4><ul><li><b>Simples:</b> como jogar uma moeda. Imprevisível, mas pode desbalancear estudos pequenos.</li><li><b>Em blocos:</b> garante tamanhos semelhantes ao longo do recrutamento (em blocos de 4: AABB, ABAB, ABBA…). Use blocos de tamanho variável e oculto.</li><li><b>Estratificada:</b> sorteio separado dentro de estratos prognósticos (idade de 65 anos ou mais, centro).</li><li><b>Minimização:</b> aloca para minimizar desequilíbrios em vários fatores; recomenda-se um componente aleatório.</li><li><b>Adaptativa por resposta:</b> as probabilidades mudam conforme resultados interinos. Exige pré-especificação e simulação.</li><li><b>Por conglomerados:</b> sorteia grupos (escolas, UBS) quando a intervenção é coletiva.</li></ul>
<div class="trap"><h4>Equilibrar em média não é igualar</h4><p>Em um ensaio pequeno, o sorteio simples pode deixar os grupos diferentes só por acaso. Isso não é viés, mas tira precisão e convence menos. Blocos, estratos e minimização existem para reduzir esse risco sem abrir mão do acaso.</p></div>`],
sigilo:["Sigilo de alocação × mascaramento",`<p>São duas proteções diferentes, separadas pelo momento da alocação.</p>
<h4>Sigilo de alocação</h4><ul><li>Atua <b>até</b> a designação: quem recruta não sabe qual será o próximo grupo.</li><li>Previne <b>viés de seleção</b>.</li><li>É sempre possível: central telefônica, sistema web, envelopes opacos, selados e numerados.</li></ul>
<h4>Mascaramento (cegamento)</h4><ul><li>Atua <b>depois</b> da designação: esconde qual tratamento cada um recebe.</li><li>Previne <b>vieses de performance e de aferição</b>.</li><li>Nem sempre é possível, mas o avaliador do desfecho quase sempre pode ser cegado.</li></ul>
<div class="trap"><h4>Um não substitui o outro</h4><p>Um ensaio duplo-cego com a sequência à vista de quem recruta continua sujeito a viés de seleção. E um ensaio aberto pode, e deve, ter sigilo de alocação.</p></div>`],
cego:["Quem está mascarado?",`<div class="tw"><table class="t"><tr><th>Tipo</th><th>Quem está mascarado</th><th>Em inglês</th></tr><tr><td>Aberto</td><td>Ninguém</td><td>Open-label</td></tr><tr><td>Simples-cego</td><td>Em geral, o participante (às vezes o avaliador)</td><td>Single-blind</td></tr><tr><td>Duplo-cego</td><td>Participante e equipe que trata e/ou avalia</td><td>Double-blind</td></tr><tr><td>Triplo-cego</td><td>Os anteriores e também o analista de dados ou o comitê</td><td>Triple-blind</td></tr></table></div>
<h4>O que cada um pode introduzir, se souber o grupo</h4><ul><li><b>Participante:</b> expectativa (efeito placebo), relato diferente dos sintomas, busca de outros tratamentos, abandono.</li><li><b>Equipe que trata:</b> atenção, ajustes e cuidados adicionais diferentes entre os grupos (viés de performance).</li><li><b>Avaliador do desfecho:</b> medida ou interpretação a favor do que espera (viés de aferição).</li><li><b>Analista:</b> escolhas de análise feitas já sabendo qual grupo é qual.</li></ul>
<h4>Mascaramento × objetividade do desfecho</h4><p>Um ensaio pode medir a intensidade da ansiedade ou o óbito. O mascaramento é mais crucial no primeiro caso.</p><ul><li>Aberto, desfecho subjetivo: <b>inaceitável</b>.</li><li>Aberto, desfecho objetivo: possível.</li><li>Cego, desfecho subjetivo: possível.</li><li>Cego, desfecho objetivo: <b>ideal</b>.</li></ul>
<div class="trap"><h4>Leia além do rótulo</h4><p>“Duplo-cego” não diz quais duas pessoas. O que importa é saber, para cada um (participante, equipe, avaliador, analista), se conhecia ou não o grupo.</p></div>`],
desfecho:["Desfecho substituto × clinicamente relevante",`<p>A doença tem uma via causal, que leva à progressão e, no fim, ao desfecho clínico. O tratamento age nessa via. O desfecho substituto é um marcador medido no meio do caminho. A sua <b>validade</b> é a capacidade de prever os eventos clínicos.</p>
<div class="tw"><table class="t"><tr><th>Condição</th><th>Desfecho substituto</th><th>Desfecho clinicamente relevante</th></tr>
<tr><td>Hipertensão</td><td>Pressão arterial</td><td>Infarto, AVC, morte</td></tr><tr><td>Dislipidemia</td><td>LDL-colesterol, perfil lipídico</td><td>Infarto, AVC, morte</td></tr><tr><td>Diabetes tipo 2</td><td>Glicemia, hemoglobina glicada</td><td>Infarto, AVC, amputação, morte</td></tr><tr><td>Câncer</td><td>Resposta tumoral, sobrevida livre de progressão</td><td>Sobrevida global, qualidade de vida</td></tr><tr><td>Doença de Alzheimer</td><td>Placa amiloide no PET</td><td>Cognição, funcionalidade, institucionalização</td></tr><tr><td>Vacinas</td><td>Resposta de anticorpos</td><td>Doença, hospitalização, morte</td></tr><tr><td>Doença renal crônica</td><td>Creatinina, TFG, albuminúria</td><td>Diálise, transplante, morte</td></tr><tr><td>Osteoporose</td><td>Densidade mineral óssea</td><td>Fratura</td></tr></table></div>
<h4>Quando o marcador enganou</h4><ul><li><b>Clofibrato</b> (hipercolesterolemia): reduziu o colesterol; no ensaio clínico, aumentou a mortalidade.</li><li><b>Flecainida</b> (extrassístoles ventriculares após infarto): reduziu as extrassístoles; aumentou a mortalidade.</li><li><b>Rosiglitazona</b> (diabetes tipo 2): reduziu a hemoglobina glicada; aumentou o infarto.</li></ul>
<div class="trap"><h4>Regra prática</h4><p>Desconfie de benefícios demonstrados apenas em marcadores.</p></div>`],
medidas:["RR, RRR, RAR e NNT",`<p><b>Risco relativo:</b> razão entre o risco do desfecho no grupo intervenção e o risco no grupo controle. RR = [a ÷ (a + b)] ÷ [c ÷ (c + d)].</p>
<ul><li><b>RR &lt; 1:</b> menor risco no grupo intervenção (efeito protetor, se o desfecho é ruim).</li><li><b>RR = 1:</b> sem diferença entre os grupos.</li><li><b>RR &gt; 1:</b> maior risco no grupo intervenção.</li></ul>
<h4>As três medidas derivadas</h4><ul><li><b>RRR</b> (redução relativa do risco) = 1 − RR: quanto do risco basal a intervenção remove, em proporção.</li><li><b>RAR</b> (redução absoluta do risco) = risco no controle − risco na intervenção, em pontos percentuais.</li><li><b>NNT</b> (número necessário tratar) = 1 ÷ RAR: quantos precisam ser tratados, por um período, para evitar um desfecho.</li></ul>
<h4>Exemplo</h4><p>Risco de óbito de 12% no controle e de 8% na intervenção: RR = 0,67; RRR = 33%; RAR = 4 pontos percentuais; NNT = 25.</p>
<h4>Impacto do tratamento</h4><div class="tw"><table class="t"><tr><th>NNT</th><th>Óbito</th><th>Eventos não fatais</th></tr><tr><td>Menor que 25</td><td>Muito grande</td><td>Grande</td></tr><tr><td>25 a 50</td><td>Grande</td><td>Moderado</td></tr><tr><td>50 a 100</td><td>Moderado</td><td>Pequeno</td></tr></table></div>
<div class="trap"><h4>Sempre com o intervalo de confiança</h4><p>Se o IC 95% inclui 1, os dados são compatíveis com ausência de efeito e, muitas vezes, também com efeitos relevantes. Ausência de evidência não é evidência de ausência. E o NNT é sempre para um tempo definido.</p></div>`],
hr:["Lendo um HR",`<ol><li><b>Interpretação igual à do RR:</b> HR menor que 1 favorece a intervenção; HR igual a 1, sem diferença. Olhe o IC.</li><li><b>Riscos proporcionais:</b> o HR supõe que a razão entre os hazards é constante no tempo. Se as curvas se cruzam, um único número resume mal.</li><li><b>Não é probabilidade:</b> HR de 0,5 não significa “metade das pessoas morre”. Significa metade da velocidade de ocorrência.</li><li><b>Olhe as curvas e os números em risco:</b> as curvas de Kaplan-Meier mostram quando o efeito aparece e quantos restam em seguimento.</li></ol>
<p>Os números em risco, abaixo das curvas, dizem quanta gente sustenta cada trecho. No fim do seguimento costumam restar poucos, e a curva fica instável.</p>`],
subgrupos:["Desfechos secundários e análises de subgrupo",`<ol><li><b>Geram hipóteses, não confirmam.</b> O desfecho primário é o que o estudo foi dimensionado para responder.</li><li><b>Multiplicidade.</b> Quanto mais comparações, mais achados “significativos” pelo acaso.</li><li><b>Subgrupos críveis</b> são pré-especificados, poucos, com teste de interação, plausíveis e replicados.</li></ol>
<h4>ISIS-2, 1988</h4><p>O ácido acetilsalicílico reduziu a mortalidade depois do infarto, exceto, aparentemente, em quem nasceu sob Gêmeos ou Libra. Os autores fizeram essa análise de propósito, para mostrar como subgrupos produzem achados espúrios.</p>
<div class="trap"><h4>A conta da multiplicidade</h4><p>Se nada funciona e cada teste tem 5% de probabilidade de dar “significativo”, com 12 subgrupos a probabilidade de pelo menos um falso positivo é 1 − 0,95¹² = 46%. O teste certo para subgrupos é o de interação (o efeito difere entre os subgrupos?), e não um teste dentro de cada fatia.</p></div>`],
hipotese:["Como classificar um ensaio clínico",`<h4>Pela hipótese</h4><ul><li><b>Superioridade:</b> o novo é melhor?</li><li><b>Não inferioridade:</b> o novo não é pior além de uma margem?</li><li><b>Equivalência:</b> é igual, dentro de uma margem?</li></ul>
<p>A margem é a maior diferença que ainda se aceitaria como clinicamente irrelevante. Ela precisa ser definida antes do estudo.</p>
<h4>Pelo objetivo</h4><ul><li><b>Terapêutico:</b> trata quem já tem a doença.</li><li><b>Preventivo:</b> vacinas, quimioprofilaxia, mudanças de estilo de vida.</li><li><b>Diagnóstico ou rastreamento:</b> estratégias de detecção.</li></ul>
<h4>Pela abordagem</h4><ul><li><b>Explanatório:</b> condições ideais (pacientes selecionados, adesão monitorada, equipes treinadas). Mede eficácia.</li><li><b>Pragmático:</b> prática real (adesão, acesso, comorbidades, sistema de saúde). Mede efetividade.</li></ul>
<div class="trap"><h4>“Sem diferença significativa” não é equivalência</h4><p>Um estudo pequeno quase sempre deixa de encontrar diferença. Equivalência e não inferioridade exigem que o intervalo de confiança inteiro fique dentro da margem.</p></div>`],
desenhos:["Ensaios pelo desenho",`<ul><li><b>Paralelo:</b> cada grupo recebe um tratamento durante todo o estudo.</li><li><b>Cruzado (crossover):</b> cada participante recebe os tratamentos em sequência, em ordem sorteada.</li><li><b>Fatorial:</b> dois ou mais tratamentos avaliados ao mesmo tempo, em combinações.</li><li><b>Por conglomerados:</b> sorteia escolas, UBS, hospitais.</li><li><b>Plataforma e adaptativo:</b> braços entram e saem do estudo conforme os resultados se acumulam.</li></ul>
<p>O desenho paralelo é o ponto de partida. Os outros existem para ganhar eficiência (cruzado, fatorial), viabilizar intervenções coletivas (conglomerados) ou testar muitos tratamentos em sequência sem recomeçar do zero (plataforma).</p>`],
fases:["As fases do desenvolvimento clínico",`<ul><li><b>Fase I, segurança:</b> 20 a 100 participantes, em geral voluntários saudáveis. Tolerabilidade, farmacocinética, dose máxima tolerada. Escalonamento de dose a partir de dados pré-clínicos.</li><li><b>Fase II, prova de conceito:</b> dezenas a algumas centenas de pacientes. Eficácia preliminar e relação dose-resposta. Frequentemente randomizada e controlada (fase IIb).</li><li><b>Fase III, confirmação:</b> centenas a milhares, em geral multicêntrica. Eficácia e segurança contra placebo ou padrão. É o ensaio confirmatório que embasa o registro.</li><li><b>Fase IV, pós-comercialização:</b> população real, muito ampla. Eventos adversos raros e de longo prazo; efetividade. Farmacovigilância, estudos observacionais e também ensaios randomizados.</li></ul>
<div class="trap"><h4>A regra de três</h4><p>Se um evento não apareceu em n pessoas, o máximo que se pode dizer, com 95% de confiança, é que ele ocorre em menos de 3 a cada n. Um ensaio de fase III com 3.000 pessoas tem só 26% de probabilidade de ver ao menos um caso de um evento que ocorre em 1 a cada 10.000.</p></div>`],
quase:["Estudos quase-experimentais",`<p>Há intervenção controlada pelo pesquisador, mas a alocação não é aleatória. Compara-se com grupos não equivalentes ou com os mesmos participantes antes da intervenção.</p>
<h4>Sem grupo controle</h4><ul><li><b>Antes e depois:</b> mede o desfecho antes e após a intervenção.</li><li><b>Séries temporais interrompidas:</b> muitas medidas antes e depois; avalia mudança de nível e de tendência.</li></ul>
<h4>Com grupo controle, sem sorteio</h4><ul><li><b>Controle não equivalente:</b> grupos comparados antes e depois.</li><li><b>Controles históricos:</b> compara com pacientes de outra época.</li></ul>
<h4>Vantagens</h4><ul><li>Viáveis quando randomizar é impraticável.</li><li>Permitem abordagem experimental quando o sorteio seria antiético ou logisticamente inviável.</li><li>Adequados para avaliar intervenções comunitárias e políticas de saúde.</li></ul>
<h4>Desvantagens</h4><ul><li>Sem sorteio, os grupos podem diferir em prognóstico.</li><li>Alguns desenhos nem têm grupo de comparação.</li><li>Inferência causal mais frágil: regressão à média, tendências seculares e eventos concomitantes.</li></ul>`],
ra:["Risco atribuível (RA) e risco atribuível populacional (RAP)",`<h4>Risco atribuível (RA)</h4><p>Diferença <b>absoluta</b> de incidência entre expostos e não expostos. Representa os casos nos expostos que podem ser atribuídos à exposição.</p><p><b>RA = incidência nos expostos − incidência nos não expostos</b></p>
<h4>Risco atribuível populacional (RAP)</h4><p>Casos na população total atribuíveis à exposição. Considera a força da associação <b>e</b> a prevalência da exposição.</p><p><b>RAP = incidência na população − incidência nos não expostos = proporção de expostos × RA</b></p>
<p>A fração atribuível na população (FAP) é o RAP dividido pela incidência na população: a proporção de todos os casos que deixaria de ocorrer sem a exposição.</p>
<h4>Exemplo ilustrativo: tabagismo e câncer de pulmão</h4><p>Incidência de 20 por 1.000 em fumantes e de 2 por 1.000 em não fumantes; 30% da população fuma.</p><ul><li>RR = 10: risco dez vezes maior.</li><li>RA = 18 por 1.000 fumantes: dos 20 casos, 18 são pelo tabagismo e 2 ocorreriam mesmo sem fumar.</li><li>RAP = 5,4 por 1.000 habitantes.</li><li>FAP = 73%: na população (7,4 casos por 1.000), cerca de 3 em cada 4 casos seriam evitados se ninguém fumasse.</li></ul>
<div class="trap"><h4>A diferença fundamental</h4><p>Ambos são “atribuíveis”, mas o RA é específico dos expostos, enquanto o RAP é da população total.</p></div>`],
relatos:["Relatos e séries de casos",`<p>Descrevem, em detalhe, pacientes com uma condição incomum, uma apresentação atípica, uma resposta inesperada a tratamento ou um evento adverso novo.</p>
<ul><li><b>Relato de caso:</b> um paciente (ou muito poucos). Profundidade clínica: história, achados, raciocínio diagnóstico, tratamento, evolução.</li><li><b>Série de casos:</b> vários pacientes com a mesma condição ou exposição, reunidos para revelar padrões comuns. Ainda sem grupo de comparação.</li></ul>
<h4>Para que servem</h4><ul><li>Identificar novas doenças ou condições.</li><li>Alertar sobre efeitos adversos raros.</li><li>Gerar hipóteses testáveis: não testam hipóteses, formulam hipóteses.</li><li>Dar pistas sobre a individualização do tratamento.</li></ul>
<h4>Relatos que mudaram a medicina</h4><ul><li><b>1961, talidomida:</b> cartas de McBride (Lancet) e de Lenz associam o fármaco a malformações de membros. Retirada do mercado; nasce a farmacovigilância moderna.</li><li><b>1981, AIDS:</b> o MMWR descreve pneumocistose em 5 homens jovens previamente saudáveis, uma série de casos. Levou à síndrome, ao HIV e aos antirretrovirais.</li><li><b>2015–16, Zika e microcefalia:</b> clínicos do Nordeste notam o excesso de microcefalia; relatos documentam o vírus no cérebro fetal.</li><li><b>2020, MIS-C:</b> série de 8 crianças no Reino Unido descreve a síndrome inflamatória multissistêmica associada ao SARS-CoV-2.</li><li><b>2021, VITT:</b> série de 11 pacientes caracteriza trombose com trombocitopenia após vacina ChAdOx1; mudou recomendações de uso.</li></ul>
<h4>Diretrizes CARE</h4><p>Estabelecem os itens mínimos de um relato rigoroso: título, resumo estruturado, informações do paciente, achados clínicos, linha do tempo, diagnóstico, intervenções, seguimento e desfechos, discussão e consentimento do paciente.</p>
<h4>Limitações</h4><ul><li>Sem grupo controle: não permitem inferência causal.</li><li>Alta suscetibilidade a vieses de seleção e de relato.</li><li>Amostra não representativa; achados não generalizáveis.</li></ul>
<p class="src">MMWR. 1981;30:250-2. Mlakar J et al. NEJM. 2016;374:951-8. Riphagen S et al. Lancet. 2020;395:1607-8. Greinacher A et al. NEJM. 2021;384:2092-101. Gagnier et al. J Clin Epidemiol 2014.</p>`]});
