/* ===================== SAIBA MAIS (conteúdo das Aulas 10, 11 e 12) ===================== */
const LEARN={
tres:["Como os desenhos se organizam",`<p>Dependendo da pergunta, do ponto em que o estudo começa e da forma de execução, as investigações epidemiológicas se classificam em modelos diferentes.</p>
<h4>Epidemiologia descritiva (descreve amostras)</h4><ul><li>Relatos e séries de casos</li><li>Transversal descritivo</li><li>Ecológico descritivo</li></ul>
<h4>Epidemiologia analítica</h4><ul><li><b>Observacional (avalia relações):</b> transversal, ecológico, caso-controle e coorte.</li><li><b>Experimental (busca causa e efeito):</b> ensaio clínico e quase-experimental.</li></ul>
<h4>As três perguntas</h4><ol><li><b>Quem decidiu a exposição?</b> O pesquisador, por sorteio: experimental. A vida, o paciente, o médico: observacional.</li><li><b>Qual é a unidade de análise?</b> O grupo (município, país): ecológico. O indivíduo: os demais.</li><li><b>Como o tempo entra?</b> Exposição e desfecho no mesmo momento: transversal. Da exposição ao desfecho: coorte. Do desfecho à exposição passada: caso-controle.</li></ol>
<div class="trap"><h4>Série de casos ou coorte?</h4><p>O que define a série de casos não é o número de pacientes, e sim a ausência de comparação. Muitas revistas chamam de relato até 3 pacientes e de série a partir de 4; outras usam 10. Atenção: uma “série” que acompanha pacientes selecionados pela exposição e mede desfechos é, na verdade, uma coorte sem controle.</p></div>
<p class="src">Dekkers OM et al. Distinguishing case series from cohort studies. Ann Intern Med. 2012;156(1):37-40.</p>`],
iceberg:["Da pirâmide aos icebergs",`<p>A pirâmide de evidências, popularizada nos anos 1990, põe revisões sistemáticas no topo, depois ensaios randomizados, coortes, caso-controle, séries de casos e opinião de especialistas. Ela tem quatro problemas:</p>
<ol><li><b>Uma pergunta só.</b> Foi desenhada para tratamentos. Para diagnóstico, prognóstico e etiologia, o desenho ideal é outro.</li><li><b>Degraus rígidos.</b> Um ensaio mal conduzido pode informar menos que uma coorte bem desenhada.</li><li><b>Síntese no “topo”.</b> Revisões sistemáticas não são um tipo de estudo primário: são uma forma de ler e combinar os demais.</li><li><b>Dados fora do quadro.</b> Dados de mundo real, registros eletrônicos, ômicas, dispositivos vestíveis e IA não têm lugar no desenho.</li></ol>
<h4>A nova pirâmide</h4><p>As linhas entre os níveis ficam onduladas: a certeza sobe ou desce conforme risco de viés, consistência, precisão e aplicabilidade. As revisões saem do topo e viram a lente com que se examina cada nível.</p>
<h4>O iceberg</h4><p>A pirâmide clássica é só a ponta. Abaixo da linha d’água estão dados de mundo real, registros eletrônicos, biossensores e vestíveis, aprendizado de máquina e IA multimodal. E há um iceberg para cada tipo de pergunta.</p>
<h4>Ferramentas de cada iceberg</h4><ul><li><b>Terapia:</b> risco de viés com RoB 2; relato com CONSORT 2025.</li><li><b>Etiologia, dano e prognóstico:</b> risco de viés com ROBINS-I e ROBINS-E; emulação de ensaio-alvo relatada pela diretriz TARGET.</li><li><b>Acurácia diagnóstica:</b> risco de viés com QUADAS-3, que substituiu o QUADAS-2; relato com STARD 2015.</li></ul>
<p class="src">Murad MH et al. New evidence pyramid. Evid Based Med. 2016;21(4):125-7. Subbiah V. The next generation of evidence-based medicine. Nat Med. 2023;29(1):49-58.</p>`],
tempo:["Direção do estudo e medida de associação",`<p>Coorte e caso-controle estudam a mesma relação entre exposição e desfecho. <b>Muda apenas a direção da investigação.</b></p>
<ul><li><b>Coorte:</b> seleciona pela exposição e segue até o desfecho.</li><li><b>Caso-controle:</b> seleciona pelo desfecho e investiga a exposição passada.</li><li><b>Transversal:</b> mede os dois no mesmo momento.</li><li><b>Ensaio clínico:</b> mesma direção da coorte, mas quem define a exposição é o pesquisador, idealmente por sorteio.</li></ul>
<h4>Toda análise parte da tabela 2×2</h4><p>a = exposto com desfecho; b = exposto sem desfecho; c = não exposto com desfecho; d = não exposto sem desfecho. Cada pessoa ocupa apenas uma das quatro células.</p>
<ul><li><b>Transversal:</b> razão de prevalências, RP = [a ÷ (a + b)] ÷ [c ÷ (c + d)].</li><li><b>Coorte e ensaio clínico:</b> risco relativo, RR = [a ÷ (a + b)] ÷ [c ÷ (c + d)], agora com casos novos.</li><li><b>Caso-controle:</b> razão de chances, OR = (a × d) ÷ (b × c).</li><li><b>Ensaio clínico:</b> também RRR = 1 − RR, RAR = risco no controle − risco na intervenção e NNT = 1 ÷ RAR.</li></ul>
<p>RP e RR usam a mesma conta. A interpretação é diferente porque uma conta casos existentes e a outra, casos novos.</p>
<div class="trap"><h4>Calcular não é interpretar</h4><p>Aqui você vê de onde a tabela vem. Para explorar a tabela (intervalos de confiança, qui-quadrado, confundimento, medidas de impacto), use o botão que abre os mesmos números no 2×2 LAB.</p></div>`],
grade:["O sistema GRADE",`<p>O GRADE (Grading of Recommendations Assessment, Development and Evaluation), adotado internacionalmente desde 2004, avalia a certeza das evidências considerando não apenas o tipo de estudo.</p>
<h4>O que reduz a certeza</h4><ul><li><b>Risco de viés:</b> problemas metodológicos que podem distorcer o resultado.</li><li><b>Inconsistência:</b> variabilidade inesperada entre estudos.</li><li><b>Imprecisão:</b> intervalos de confiança amplos, amostras pequenas.</li><li><b>Evidência indireta:</b> diferença entre a pergunta e a população do estudo.</li><li><b>Viés de publicação:</b> tendência de não publicar resultados negativos.</li></ul>
<h4>O que pode elevar a certeza de estudos observacionais</h4><ul><li>Efeito de grande magnitude.</li><li>Gradiente dose-resposta.</li><li>Confundidores plausíveis que, se atuassem, reduziriam o efeito observado.</li></ul>
<h4>Os quatro níveis</h4><p>Alta, moderada, baixa e muito baixa. Conjuntos de ensaios randomizados começam em alta; conjuntos de estudos observacionais, em baixa.</p>
<div class="trap"><h4>Qualidade não é só o rótulo do desenho</h4><p>É isso que as linhas onduladas da nova pirâmide representam: a certeza sobe ou desce conforme risco de viés, consistência, precisão e aplicabilidade.</p></div>
<p class="src">Guyatt et al. BMJ 2008. Schünemann et al. Cochrane Handbook 2022.</p>`],
foto:["Estudo transversal",`<p>Estudo observacional em que exposição e desfecho são medidos no mesmo momento (ou em um período curto), em uma amostra de uma população definida. Também chamado seccional, de corte transversal, inquérito ou estudo de prevalência.</p>
<ul><li><b>Mede</b> prevalência (casos existentes), não incidência.</li><li><b>Pode ser</b> descritivo (quanto?) ou analítico (associado a quê?).</li></ul>
<h4>Quando optar</h4><ul><li>Medir e descrever a frequência de doenças e de fatores de risco conhecidos.</li><li>Gerar hipóteses etiológicas para estudos analíticos mais robustos.</li><li>Avaliar doenças crônicas e de baixa letalidade, que têm mais probabilidade de estar presentes no momento da coleta.</li><li>Avaliar e planejar serviços de saúde.</li></ul>
<h4>Quando não serve</h4><p>Doenças raras têm baixa prevalência e exigem amostras enormes. Doenças agudas e letais duram pouco: os pacientes somem da amostra.</p>
<div class="trap"><h4>Viés de prevalência e de sobrevivência</h4><p>Doenças de maior duração têm mais probabilidade de ser encontradas que as de curso curto. Quem morre depressa ou se cura em pouco tempo não é capturado, o que subestima as formas graves e superestima as formas crônicas e leves.</p></div>
<h4>Vantagens</h4><ul><li>Rápidos e de baixo custo, sem seguimento.</li><li>Fornecem dados de prevalência para o planejamento em saúde.</li><li>Permitem estudar várias exposições e desfechos ao mesmo tempo.</li></ul>`],
reversa:["Temporalidade no estudo transversal",`<p>No estudo transversal não se sabe se a exposição precedeu o desfecho. A simultaneidade impede definir a direção.</p>
<h4>Três leituras para a mesma associação</h4><ul><li>A exposição causa o desfecho.</li><li><b>Causalidade reversa:</b> o desfecho leva à exposição.</li><li><b>Confundimento:</b> um terceiro fator, associado aos dois, produz a associação.</li></ul>
<h4>Outros vieses do desenho</h4><ul><li><b>Seleção:</b> dificuldade de definir a base populacional adequada.</li><li><b>Informação e memória:</b> doentes tendem a lembrar melhor de exposições passadas; medidas subjetivas introduzem ruído.</li></ul>
<h4>Para minimizar</h4><p>Amostras aleatórias, definição clara dos critérios de desfecho, questionários validados e tamanho de amostra calculado.</p>
<div class="trap"><h4>Associação não é causa</h4><p>Uma RP com intervalo de confiança que exclui 1 é compatível com um efeito real, o que não significa causalidade.</p></div>`],
falacia:["Estudos ecológicos",`<p>A unidade de análise é o grupo ou a população, nunca o indivíduo. As medidas de exposição e de desfecho são agregadas por unidades populacionais e comparadas entre si.</p>
<h4>Tipos de medida</h4><ul><li><b>Agregadas:</b> resumo de dados individuais do grupo (taxa de mortalidade infantil, proporção de fumantes).</li><li><b>Ambientais:</b> características físicas do lugar (poluição do ar, flúor na água, temperatura média).</li><li><b>Globais:</b> atributos do grupo sem equivalente individual (tipo de sistema de saúde, PIB per capita, legislação).</li></ul>
<h4>Tipos de desenho</h4><ul><li><b>Exploratório</b> (descreve padrões) ou <b>analítico</b> (mede e testa a associação).</li><li>De <b>múltiplos grupos</b>, de <b>tendência temporal</b> ou <b>misto</b>.</li></ul>
<div class="trap"><h4>Falácia ecológica</h4><p>Erro de interpretação que ocorre quando se fazem inferências sobre indivíduos com base em dados agregados de grupos. O que se observa no grupo não se aplica, necessariamente, a cada pessoa dentro dele.</p></div>
<h4>Vantagens</h4><ul><li>Baixo custo e rapidez: usam dados secundários já disponíveis (DATASUS, IBGE, GBD).</li><li>Geram hipóteses em nível populacional.</li><li>Medem efeitos que só existem no grupo (o efeito do PIB na saúde, por exemplo).</li></ul>
<h4>Limitações</h4><ul><li>Não permitem extrapolar para indivíduos.</li><li>Sem dados individuais, não há como controlar confundidores.</li><li>Dependem de fontes de dados confiáveis e comparáveis.</li></ul>
<p>Os resultados de um estudo ecológico devem ser comparados com estudos que tenham dados individuais.</p>`],
taxas:["Razão de taxas",`<p>Taxa = número de eventos ÷ população, multiplicado por uma base (1.000, 10.000 ou 100.000 habitantes) para facilitar a leitura.</p>
<p><b>Razão de taxas (RT) = taxa em A ÷ taxa em B.</b> Uma RT de 1,25 significa que a taxa em A é 25% maior que em B.</p>
<div class="trap"><h4>Cuidado</h4><p>A comparação direta não controla fatores de confusão, como estrutura etária, poluição e cobertura de serviços de saúde. Dois municípios podem ter taxas diferentes só porque um deles tem população mais idosa.</p></div>`],
seguimento:["Estudo de coorte",`<p>Estudo observacional longitudinal em que pessoas livres do desfecho são classificadas segundo a exposição e acompanhadas no tempo, comparando-se a incidência do desfecho entre expostos e não expostos.</p>
<h4>Quando optar</h4><ol><li><b>Medir incidência:</b> é a forma de obter o RR diretamente.</li><li><b>Sequência temporal:</b> estabelecer que a exposição precede o desfecho.</li><li><b>Fatores de risco conhecidos:</b> medir frequência e características das exposições.</li><li><b>Múltiplos desfechos</b> para uma mesma exposição.</li><li><b>História natural:</b> evolução e prognóstico de uma doença.</li></ol>
<h4>Medidas</h4><ul><li><b>Incidência acumulada</b> = casos novos ÷ população em risco no início.</li><li><b>Risco relativo (RR)</b> = incidência nos expostos ÷ incidência nos não expostos.</li><li><b>Risco atribuível (RA)</b> = incidência nos expostos − incidência nos não expostos.</li><li><b>Risco atribuível populacional (RAP)</b> = incidência na população − incidência nos não expostos.</li></ul>
<h4>Vieses e como prevenir</h4><ul><li><b>Seleção:</b> autosseleção ou perda diferencial de seguimento. Manter contato periódico, buscar dados com familiares e fazer análise de sensibilidade com os piores cenários.</li><li><b>Informação:</b> erros de medição. Instrumentos validados, treinamento e cegamento para a exposição quando possível.</li><li><b>Confundimento:</b> variável associada à exposição e ao desfecho. Medir os confundidores e ajustar na análise, estratificar ou emparelhar.</li></ul>
<h4>Desvantagens</h4><ul><li>A prospectiva custa caro e demora.</li><li>Inadequada para doenças raras e para doenças com longo período de latência.</li></ul>`],
prosp:["Coorte retrospectiva × caso-controle",`<p>“Retrospectivo” descreve onde estão os dados, não o desenho. Uma coorte pode ser inteiramente retrospectiva.</p>
<div class="tw"><table class="t"><tr><th>Critério</th><th>Coorte retrospectiva</th><th>Caso-controle</th></tr>
<tr><td>Seleção por</td><td>Exposição</td><td>Desfecho</td></tr><tr><td>Medida principal</td><td>Incidência, RR, RA</td><td>Odds ratio</td></tr><tr><td>Desfechos raros</td><td>Exige bases enormes</td><td>Eficiente</td></tr><tr><td>Exposições raras</td><td>Eficiente</td><td>Ineficiente</td></tr><tr><td>Temporalidade</td><td>Clara, se o registro da exposição antecede o desfecho</td><td>Pode ser ambígua</td></tr><tr><td>Múltiplos…</td><td>desfechos</td><td>exposições</td></tr></table></div>
<div class="trap"><h4>O critério</h4><p>Pergunte como as pessoas entraram no estudo. Se foi pela exposição, é coorte. Se foi pelo desfecho, é caso-controle.</p></div>`],
orrr:["Razão de chances (odds ratio)",`<p><b>OR = chance de exposição nos casos ÷ chance de exposição nos controles = (a ÷ c) ÷ (b ÷ d) = (a × d) ÷ (b × c).</b></p>
<p>Com a exposição nas linhas e o desfecho nas colunas, a e c são os casos; b e d, os controles.</p>
<h4>Por que não o RR?</h4><p>O pesquisador fixa o número de casos e de controles. Se escolho 100 casos e 100 controles, metade da amostra “tem a doença” por decisão minha. A proporção de doentes entre expostos, a ÷ (a + b), é artificial: basta dobrar os controles para o “risco” mudar.</p>
<h4>A simetria da OR</h4><p>A chance de exposição (casos ÷ controles) e a chance de doença (expostos ÷ não expostos) levam ao mesmo número: ad ÷ bc. Por isso a OR funciona nos dois sentidos.</p>
<h4>Interpretação</h4><ul><li><b>OR = 1:</b> sem associação.</li><li><b>OR &gt; 1:</b> exposição mais frequente entre os casos.</li><li><b>OR &lt; 1:</b> exposição menos frequente entre os casos; possível proteção.</li></ul>
<div class="trap"><h4>Chance não é risco</h4><p>A OR se aproxima do RR quando a doença é rara na população (regra prática: menos de 10%). Fora disso, descreva como “chance” e não leia a OR como RR.</p></div>
<h4>Quando usar o caso-controle</h4><ul><li>Doença rara ou com longo período de latência.</li><li>Epidemias de causa desconhecida e surtos.</li><li>Várias exposições para um único desfecho.</li><li>Recursos limitados ou urgência na resposta.</li></ul>`],
memoria:["Vieses no caso-controle",`<ul><li><b>Viés de memória (recordação):</b> casos tendem a lembrar mais, ou de forma diferente, das exposições passadas, sobretudo quando sabem que se busca uma causa para a doença.</li><li><b>Viés de informação:</b> erros na classificação da exposição ou do desfecho. Podem ser diferenciais (afetam casos e controles de modo diferente) ou não diferenciais.</li><li><b>Viés de seleção:</b> os controles não representam a população de origem dos casos.</li></ul>
<h4>Como prevenir</h4><ul><li>Fontes independentes da memória: prontuários e registros.</li><li>Entrevistador cego para a condição de caso ou controle.</li><li>Instrumentos validados e marcadores objetivos de exposição.</li><li>Controles com doença que exija a mesma atenção à exposição.</li></ul>
<div class="trap"><h4>Direção do erro</h4><p>O erro não diferencial costuma enfraquecer a associação. O erro diferencial pode aumentar ou diminuir a OR, e por isso preocupa mais.</p></div>`],
controles:["A escolha dos controles",`<p>Os controles devem representar a exposição na mesma população que originou os casos. Um bom teste: se esse controle tivesse adoecido, teria entrado no estudo como caso?</p>
<ul><li><b>Populacionais:</b> amostra aleatória da população-base. Ideal, porém mais caro.</li><li><b>Hospitalares:</b> acessíveis e cooperativos; há risco de viés de Berkson se a doença do controle se associa à exposição.</li><li><b>Vizinhança e amigos:</b> semelhança socioeconômica; há risco de pareamento excessivo na exposição.</li><li><b>Pareamento:</b> controla confundidores como idade e sexo, mas exige análise pareada e impede estimar o efeito da variável pareada.</li></ul>
<p>A seleção dos controles é a etapa mais crítica e mais difícil do desenho.</p>`],
sorteio:["Por que randomizar",`<p>Ensaios clínicos e coortes são longitudinais e acompanham a incidência de desfechos. Mas, na coorte, quem escolhe a exposição é a vida.</p>
<ol><li><b>Confundimento por indicação:</b> pacientes mais graves tendem a receber mais tratamento. O prognóstico decide a exposição.</li><li><b>Efeito do usuário saudável:</b> quem adere a um tratamento preventivo costuma ter outros hábitos que protegem.</li><li><b>A randomização rompe esse vínculo:</b> o sorteio não conhece o prognóstico. Os grupos ficam comparáveis em média, inclusive em fatores nunca medidos.</li></ol>
<p>Um exemplo histórico: em coortes, usuárias de terapia hormonal na pós-menopausa pareciam ter menos doença coronariana. O ensaio randomizado não mostrou proteção. As usuárias eram, desde o início, mais saudáveis.</p>
<h4>Formas de randomizar</h4><ul><li><b>Simples:</b> como jogar uma moeda. Imprevisível, mas pode desbalancear estudos pequenos.</li><li><b>Em blocos:</b> garante tamanhos semelhantes ao longo do recrutamento. Os blocos devem ter tamanho variável e oculto.</li><li><b>Estratificada:</b> sorteio separado dentro de estratos prognósticos (idade, centro).</li><li><b>Minimização:</b> aloca para reduzir desequilíbrios em vários fatores.</li><li><b>Adaptativa por resposta:</b> as probabilidades mudam conforme resultados interinos.</li><li><b>Por conglomerados:</b> sorteia grupos (escolas, UBS) quando a intervenção é coletiva.</li></ul>
<div class="trap"><h4>Sigilo de alocação não é mascaramento</h4><p>O <b>sigilo de alocação</b> atua até a designação: quem recruta não sabe qual será o próximo grupo. Previne viés de seleção e é sempre possível. O <b>mascaramento</b> atua depois: esconde qual tratamento cada um recebe e previne vieses de performance e de aferição.</p></div>`],
efeito:["O que o ensaio clínico desconta",`<p>Quatro fenômenos fazem pacientes melhorar sem que o tratamento tenha efeito:</p>
<ul><li><b>História natural da doença:</b> muitas condições melhoram sozinhas.</li><li><b>Regressão à média:</b> quem é selecionado por um valor extremo tende a apresentar valores menos extremos depois.</li><li><b>Efeito Hawthorne:</b> pessoas mudam de comportamento por saberem que estão sendo observadas.</li><li><b>Efeito placebo:</b> a expectativa de receber um tratamento altera sintomas.</li></ul>
<h4>Estudos quase-experimentais</h4><p>Há intervenção controlada pelo pesquisador, mas a alocação não é aleatória.</p><ul><li><b>Sem grupo controle:</b> antes e depois; séries temporais interrompidas.</li><li><b>Com grupo controle, sem sorteio:</b> controle não equivalente; controles históricos.</li></ul>
<p>São viáveis quando randomizar é impraticável ou antiético e servem para avaliar intervenções comunitárias e políticas de saúde. A inferência causal é mais frágil: regressão à média, tendências seculares e eventos concomitantes.</p>
<h4>Quem está mascarado?</h4><ul><li><b>Aberto:</b> ninguém.</li><li><b>Simples-cego:</b> em geral, o participante.</li><li><b>Duplo-cego:</b> participante e equipe que trata ou avalia.</li><li><b>Triplo-cego:</b> os anteriores e também o analista de dados ou o comitê.</li></ul>
<div class="trap"><h4>Mascaramento e tipo de desfecho</h4><p>Quanto mais subjetivo o desfecho, mais o mascaramento importa. Estudo aberto com desfecho subjetivo (intensidade de ansiedade) é inaceitável; com desfecho objetivo (óbito), é possível. O ideal é estudo cego com desfecho objetivo.</p></div>`],
rm:["Regressão à média",`<p>Toda medida tem uma parte estável e uma parte que varia de um dia para o outro. Quando se escolhem pessoas pelo valor mais alto de uma única medida, escolhem-se, em parte, pessoas que estavam em um dia de valor alto.</p>
<p>Na medida seguinte, a parte variável muda e o valor tende a se aproximar da média da própria pessoa. A média do grupo cai sem que nada tenha sido feito.</p>
<h4>O que aumenta a regressão</h4><ul><li>Corte de seleção mais extremo.</li><li>Maior variação entre uma medida e outra.</li></ul>
<div class="trap"><h4>Por que importa</h4><p>Pacientes procuram tratamento quando estão piores. Em um estudo antes e depois, a melhora por regressão à média se soma à história natural e é confundida com o efeito do tratamento. Um grupo controle selecionado do mesmo jeito regride igual, e a diferença entre os grupos fica livre desse efeito.</p></div>`],
itt:["Intenção de tratar × por protocolo",`<h4>Intenção de tratar (ITT)</h4><ul><li>Analisa cada participante no grupo para o qual foi sorteado, tenha ou não aderido.</li><li>Preserva a randomização e a comparabilidade dos grupos.</li><li>Estima o efeito de oferecer o tratamento, próximo da efetividade.</li><li>A não adesão tende a diluir o efeito em direção ao nulo.</li><li>É a análise principal em ensaios de superioridade.</li></ul>
<h4>Por protocolo (PP)</h4><ul><li>Analisa apenas quem seguiu o protocolo como planejado.</li><li>Exclui não aderentes, cruzamentos e violações.</li><li>Quebra a randomização: quem adere difere de quem não adere.</li><li>Pode enviesar o resultado em qualquer direção.</li><li>É relatada junto com a ITT, sobretudo em ensaios de não inferioridade.</li></ul>
<h4>Eficácia × efetividade</h4><p><b>Eficácia</b> é o efeito da intervenção em condições ideais: pacientes selecionados, adesão monitorada, equipes treinadas (ensaio explanatório). <b>Efetividade</b> é o resultado no mundo real, com adesão, acesso, comorbidades e sistema de saúde (ensaio pragmático).</p>`],
forest:["Revisão sistemática e metanálise",`<h4>Como ler um forest plot</h4><ul><li><b>Quadrado:</b> a estimativa de cada estudo. O tamanho indica o peso na análise.</li><li><b>Linha horizontal:</b> o intervalo de confiança de 95% daquele estudo.</li><li><b>Linha vertical:</b> a nulidade (RR = 1), nenhum efeito.</li><li><b>Losango:</b> a estimativa combinada. O centro é o efeito; as pontas, o IC de 95%.</li></ul>
<p>O I² indica quanto da variação entre os estudos vai além do que o acaso explicaria. O modelo de efeito fixo supõe um único efeito verdadeiro; o de efeitos aleatórios admite que o efeito varie entre os estudos e produz um intervalo mais largo quando há heterogeneidade.</p>
<h4>Revisão sistemática</h4><ul><li>É um método de pesquisa sobre pesquisas: não gera dados novos, mas é um estudo em si, com protocolo e métodos próprios.</li><li>Minimiza vieses e erros aleatórios pela busca exaustiva, seleção explícita e síntese estatística.</li><li>Sua qualidade depende dos estudos incluídos e do julgamento de quem decide o que é combinável.</li><li>Pode ou não ter metanálise.</li></ul>
<h4>Tipos de revisão</h4><ul><li><b>Narrativa:</b> panorama e discussão conceitual; as fontes são escolhidas pelo autor.</li><li><b>Integrativa:</b> integra evidências de naturezas diferentes.</li><li><b>De escopo:</b> mapeia o que existe e identifica lacunas.</li><li><b>Sistemática:</b> responde a uma pergunta específica (PICO), com protocolo registrado, busca reprodutível em várias bases, dois revisores independentes, avaliação do risco de viés e certeza graduada pelo GRADE.</li></ul>
<div class="trap"><h4>Importante</h4><p>Compilar estudos duvidosos gera uma metanálise igualmente duvidosa.</p></div>`]};
